### ISSUE TITLE
Option to enable retroachievements still not present in the flatpak version of flycast

### ISSUE THREAD

**Issue by krauser87** [flathub/org.flycast.Flycast#206]
As the title says, the flatpak version still doesn't have the option to log in into your retroachievements account unlike the appimages for both the master and the dev brands.

**Comment by flyinghead** [comment]
Are you sure you are running v2.4?
I just installed the test build and retro achievements are there.

**Comment by krauser87** [comment]
The version I get from installing it via flathub repo is the v2.3.2 version

```
flatpak info org.flycast.Flycast 

Flycast - Sega Dreamcast, Naomi and Atomiswave emulator

          ID: org.flycast.Flycast
         Ref: app/org.flycast.Flycast/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: v2.3.2
     License: GPL-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 34.0 MB
     Runtime: org.freedesktop.Platform/x86_64/24.08
         Sdk: org.freedesktop.Sdk/x86_64/24.08

      Commit: 20f5bb4ff616620e3118cc378f0f3b2b40233d20aabb41ce683f693ff26f46f0
      Parent: efd195543818a03cdeb864e07e926283542b736b563595b9a798d29b6f101e4b
     Subject: Update runtime to 24.08 (96f47ced)
        Date: 2024-09-28 19:27:59 +0000

```

**Comment by flyinghead** [comment]
Right, v2.4 hasn't been published yet. It will be in the next 24H or so.
In the mean time:
`flatpak install --user https://dl.flathub.org/build-repo/139615/org.flycast.Flycast.flatpakref`

**Comment by krauser87** [comment]
Thank you, @flyinghead

**Comment by j8r** [comment]
https://github.com/flathub/org.flycast.Flycast/pull/205 merged, the issue can be closed.
