### ISSUE TITLE
Flycast does not launch on Raspberry Pi OS

### ISSUE THREAD

**Issue by RGarciaLago** [flathub/org.flycast.Flycast#207]
I installed Flycast utilizing Flatpak and the application does not appear when I attempt to launch it from the start menu. I'm on a Raspberry Pi 5 8GB model running the 64-bit of Bookworm on kernel version 6.6.

Please let me know if there's any other information you'd like, thank you.

**Comment by flyinghead** [comment]
Some logs would greatly help. Try `flatpak run org.flycast.Flycast` from a terminal

**Comment by RGarciaLago** [comment]
Thank you so much for your response. Here's the terminal log:
```
is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:42:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:43:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:44:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:45:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:46:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:47:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:48:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: too many errors
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: failed to parse file
00:00:000 ui/gui.cpp:3718 E[COMMON]: Verify Failed  : PAGE_MASK==(sysconf(_SC_PAGESIZE)-1)
 in common_linux_setup -> /run/build/flycast/core/linux/common.cpp : 184
```

**Comment by RGarciaLago** [comment]
I tried running it again because the UTF-8 string errors seemed out of place and I got the following:
```
00:00:000 ui/gui.cpp:3718 E[COMMON]: Verify Failed  : PAGE_MASK==(sysconf(_SC_PAGESIZE)-1)
 in common_linux_setup -> /run/build/flycast/core/linux/common.cpp : 184
```

**Comment by flyinghead** [comment]
Yes, this is the root cause of the issue.
The linux kernel shipped with the Raspberry Pi 5 uses a 16K page size by default. Unfortunately the Flycast flatpak binary is built for a 4K page, which is found on most linux systems. There is no easy way to have a dynamic page size so a special binary must be built for the Rpi 5.
I'm not sure if flatpak allows this and how it can be done.
The alternative is to build Flycast locally.

**Comment by RGarciaLago** [comment]
Thanks for looking into the issue! I'll go ahead and close the bug then.
