### ISSUE TITLE
v2.0 has been released

### ISSUE THREAD

**Issue by Kirtai** [flathub/org.flycast.Flycast#4]
as per the title

**Comment by j8r** [comment]
It is currently used here because master is tracked.
@flyinghead do you think we should rather track releases instead?

I think it could be better, especially that the Flatpak is quite proven now.

**Comment by j8r** [comment]
Ok then, fine by me! But what's the purpose of this releases?
Even though the Flathub politic is to submit stable software, Flycast master has been historically quite stable.

**Comment by flyinghead** [comment]
Mostly to make it easy for people landing on the project page looking for github releases. Also CI builds are only kept 3 months so it's a way to have longer-term archival of past builds. And it forces me to make release notes for each one.
