### ISSUE TITLE
Is host filesystem access necessary?

### ISSUE THREAD

**Issue by garrhow** [flathub/org.flycast.Flycast#5]
What is the reason behind exposing the host filesystem? I would think access to only the home directory would be more preferable.

**Comment by j8r** [comment]
It is used to access the game roms, which can be anywhere in the filesystem: `/mnt`, `/home`, `/media` or other locations.
By the way reading home or the whole system doesn't change much in therms of security: the biggest place by far with sensitive data is `/home`, where personal ones are.

**Comment by garrhow** [comment]
Oh, got it. Thanks!
